### ISSUE TITLE
clock is not run

### ISSUE THREAD

**Issue by hf-t** [lexrus/LexClockWidget#2]

**Comment by gogoqaz** [comment]
same here with Xcode 12.0.1 & iOS 14.0.1

**Comment by Suzhenyu** [comment]
same here with Xcode 12.0 & iOS 14.0

**Comment by VinceXR** [comment]
clock only run on app alive , because the cutdown apply on tick() function

**Comment by lexrus** [comment]
https://stackoverflow.com/questions/66258627/ios-clock-animations-on-homescreen-widget
