### ISSUE TITLE
大佬，在xcode14上之后，时钟不能按秒刷新了呢？

### ISSUE THREAD

**Issue by Jdb156158** [lexrus/LexClockWidget#4]
struct LexClockWidgetEntryView : View {
    var entry: Provider.Entry

    private static let longDateFormat: DateFormatter = {
        let formatter = DateFormatter()
        formatter.dateFormat = "HH:mm:ss"
        return formatter
    }()

    var body: some View {
        VStack {
            ClockView()
            Text("\(entry.date, formatter: Self.longDateFormat)")
                    .font(.footnote)
                .onAppear {
                    tick()
                }
        }
        .padding(.vertical, 10)
    }

    private func tick() {
        DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
            WidgetCenter.shared.reloadAllTimelines()
                tick()
        }
    }
}

**Comment by lexrus** [comment]
用 private api:
[_clockHandRotationEffect](https://stackoverflow.com/questions/66258627/ios-clock-animations-on-homescreen-widget)
